// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjjhgllqdxtwdxifzvvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqamhnbGxxZHh0d2R4aWZ6dnZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODk5MDAsImV4cCI6MjA1Nzc2NTkwMH0.Fkt3nfz8krKlZHTdI1MfIjxthZ4rqAV3K3iVNYVpYb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);